spring:
  datasource:
    url: jdbc:sqlserver://ds-project-db.database.windows.net:1433;database=CarRecommendation
    username: car_admin@car-recommendation@ds-project-db
    password: P@rol@32
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080